export const MOMENT_REQUIRED_WIDTH = 1080;
export const MOMENT_REQUIRED_HEIGHT = 1674;
export const MOMENT_REQUIRED_RATIO =
    MOMENT_REQUIRED_HEIGHT / MOMENT_REQUIRED_WIDTH;
export const MOMENT_BORDER_RADIUS = 50;
